language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip install -r requirements.txt

script:
  - cd mysite
  - python manage.py makemigrations
  - python manage.py migrate
  - cd ..
  - coverage run --source=./mysite/ mysite/manage.py test pynny
  - coverage report -m

after_script: coveralls

