language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

install: 
    - pip install -r requirements.txt

script:
    - coverage run --source=mysite/ mysite/manage.py test
    - coverage report -m

after_script: coveralls

