language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_STATIC_ROOT=static/
  - DJANGO_SECRET_KEY=r\'+)c&*P#LM/3xchu$"2j~5[x3A\\3wm$1#u_3LKeaYG{~\'+zlZ
  - DJANGO_DEBUG=1
  - DJANGO_SESSION_COOKIE_HTTPONLY=""
  - DJANGO_SESSION_COOKIE_SECURE=""
  - DJANGO_X_FORWARDED_PROTO=http

install: 
  - pip install -r requirements.txt
  - pip install codecov

script:
  - cd mysite
  - python manage.py makemigrations
  - python manage.py migrate
  - cd ..
  - coverage run --source=./mysite/ --omit=mysite/manage.py,mysite/wsgi.py mysite/manage.py test pynny
  - coverage report -m

after_script: codecov

