language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip install -r requirements.txt
  - pip install codecov

script:
  - cd mysite
  - python manage.py makemigrations
  - python manage.py migrate
  - cd ..
  - coverage run --source=./mysite/ --omit=mysite/manage.py,mysite/wsgi.py mysite/manage.py test pynny
  - coverage report -m

after_script: codecov

