language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

services:
    - sqlite3

env:
    - DJANGO=1.11 DB=sqlite3

# Install dependencies
install: 
    - pip install -q Django==$DJANGO

before_script:
    - python mysite/manage.py makemigrations
    - python mysite/manage.py migrate

script:
    - python mysite/manage.py test
