language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

services:
    - mysql

env:
    -DJANGO=1.11 DB=mysql

# Install dependencies
install: 
    - pip install -r requirements.txt

before_script:
    - mysql -e 'create database test;' -u root

# Command to run tests
script: 
    - python mysite/manage.py test
