language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

dist: trusty
sudo: required

services:
    - msyql

env:
    - DJANGO=1.11 DB=mysql

# Install dependencies
install: 
    - pip install mysqlclient
    - pip install -q Django==$DJANGO

before_script:
    - mysql -e 'SELECT database djangodb;'

script:
    - python mysite/manage.py test
